apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: aks07hat/dummy
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom: 
            ConfigMapKeyRef:
              name: my-config
              key: host
        - name: DB_NAME
          valueFrom: 
            ConfigMapKeyRef:
              name: my-config
              key: name
        - name: DB_USER
          valueFrom: 
            ConfigMapKeyRef:
              name: my-secret
              key: username
        - name: DB_PASSWORD
          valueFrom: 
            ConfigMapKeyRef:
              name: my-secret
              key: password                                         